include:
  - remote: "https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/48c2c583/templates/fedora.yml"

stages:
  - container
  - test

variables:
  FDO_UPSTREAM_REPO: malureau/rdw
  GIT_SUBMODULE_STRATEGY: recursive

.rdw.fedora:42:
  variables:
    FDO_DISTRIBUTION_VERSION: '42'
    FDO_DISTRIBUTION_TAG: "2025-07-22.0"

build-fedora-container:
  extends:
    - .fdo.container-build@fedora@x86_64
    - .rdw.fedora:42
  stage: container
  variables:
    FDO_DISTRIBUTION_PACKAGES: >-
      cargo
      freerdp2-devel
      git
      gobject-introspection-devel
      gstreamer1-devel
      gstreamer1-plugins-base-devel
      gtk4-devel
      gvnc-devel
      libadwaita-devel
      libepoxy-devel
      openssl-devel
      rust
      spice-glib-devel
      spice-gtk3-vala
      usbredir-devel
      vala
    FDO_DISTRIBUTION_EXEC: >-
      cargo install cargo-c

test-build:
  extends:
    - .fdo.distribution-image@fedora
    - .rdw.fedora:42
  stage: test
  script:
    - | # build librdw
      pushd rdw4
      make
      sudo make install
      popd
    - cargo build # build the demo, no bindings
    - | # build librdw-*
      for i in rdw4-rdp rdw4-spice rdw4-vnc; do
        pushd $i
        make
        sudo make install
        popd
      done
