include:
  - remote: "https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/e195d80f/templates/fedora.yml"

stages:
  - container
  - test

variables:
  FDO_UPSTREAM_REPO: malureau/rdw
  GIT_SUBMODULE_STRATEGY: recursive

.rdw.fedora:41:
  variables:
    FDO_DISTRIBUTION_VERSION: '41'
    FDO_DISTRIBUTION_TAG: "2024-10-30.1"

build-fedora-container:
  extends:
    - .fdo.container-build@fedora@x86_64
    - .rdw.fedora:41
  stage: container
  variables:
    FDO_DISTRIBUTION_PACKAGES: >-
      cargo
      freerdp-devel
      git
      gobject-introspection-devel
      gstreamer1-devel
      gstreamer1-plugins-base-devel
      gtk4-devel
      gvnc-devel
      libadwaita-devel
      openssl-devel
      rust
      spice-glib-devel
      usbredir-devel
      vala
    FDO_DISTRIBUTION_EXEC: >-
      cargo install cargo-c

test-build:
  extends:
    - .fdo.distribution-image@fedora
    - .rdw.fedora:41
  stage: test
  script:
    - pushd rdw4
    - make
    - sudo make install
    - popd
    - cargo build
