[package]
name = "rdw4-rdp"
version = "0.1.0"
authors = ["Marc-André Lureau <marcandre.lureau@redhat.com>"]
edition = "2021"

[features]
default = []
bindings = ["rdw/bindings"]
capi = []

[build-dependencies]
cargo_metadata = "0.19"
cbindgen = { path = "../cbindgen", features = ["gobject"] }
system-deps = "7.0"

[package.metadata.system-deps]
rdw4-rdp = { version = "0.1", feature = "bindings" }

[dependencies]
log = "0.4"
derivative = "2.2.0"
rdw = { package = "rdw4", path = "../rdw4", default-features = false }
freerdp = { package = "freerdp2", git = "https://github.com/elmarco/freerdp-rs.git" }
nix = { version = "0.29", features = ["fs", "event"] }
futures-executor = "0.3"
futures-util = "0.3"
futures-channel = "0.3"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.60", features = [
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_Security",
] }

[package.metadata.capi.library]
name = "rdw4-rdp"

[package.metadata.capi.header]
name = "rdw-rdp"
subdirectory = "rdw4"
generation = false

[package.metadata.capi.pkg_config]
filename = "rdw4-rdp"
requires = ["rdw4", "freerdp2"]
