[package]
name = "rdw4-rdp"
version = "0.2.0"
authors = ["Marc-André Lureau <marcandre.lureau@redhat.com>"]
edition = "2021"

[features]
default = []
bindings = ["rdw/bindings"]
capi = []

[build-dependencies]
cargo_metadata.workspace = true
cbindgen = { path = "../cbindgen", features = ["gobject"] }
system-deps = "9.0"

[package.metadata.system-deps]
rdw4-rdp = { version = "0.1", feature = "bindings" }

[dependencies]
ironrdp = { version = "0.17.0", features = [
    "cliprdr",
    "dvc",
    "displaycontrol",
    "session",
    "connector",
    "rdpdr",
    "graphics",
    "pdu",
    "rdpsnd",
] }
ironrdp-tokio = { version = "0.10", features = ["reqwest"] }
ironrdp-tls = { version = "0.2.2", features = ["native-tls"] }
x509-cert = { version = "0.2", default-features = false, features = ["std"] }
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["net", "rt", "macros"] }
derivative = "2.2.0"
rdw = { package = "rdw4", path = "../rdw4", default-features = false }
nix = { version = "0.31", features = ["fs", "event"] }
futures-executor = "0.3"
futures-util = "0.3"
futures-channel = "0.3"
tracing = "0.1"
whoami = "2.1"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = [
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_Security",
] }

[package.metadata.capi.library]
name = "rdw4-rdp"

[package.metadata.capi.header]
name = "rdw-rdp"
subdirectory = "rdw4"
generation = false

[package.metadata.capi.pkg_config]
filename = "rdw4-rdp"
requires = ["rdw4"]
