[alias]
xtask = "run --package xtask --"

[patch.crates-io]
ironrdp = { git = "https://github.com/Devolutions/IronRDP.git" }
ironrdp-tokio = { git = "https://github.com/Devolutions/IronRDP.git" }
#ironrdp = { path = "../IronRDP/crates/ironrdp" }
#ironrdp-tokio = { path = "../IronRDP/crates/ironrdp-tokio" }
