[package]
name = "rdw4-qemu"
version = "0.1.0"
authors = ["Marc-André Lureau <marcandre.lureau@redhat.com>"]
edition = "2021"

[features]
default = []
bindings = ["rdw/bindings"]
capi = []

[build-dependencies]
cargo_metadata.workspace = true
cbindgen = { path = "../cbindgen", features = ["gobject"] }
system-deps = "9.0"

[package.metadata.system-deps]
rdw4-qemu = { version = "0.1", feature = "bindings" }

[dependencies]
log = "0.4"
zbus = { version = "5.0", features = ["p2p", "serde_bytes"] }
futures-util = "0.3"
futures = "0.3"
async-trait = "0.1"
pixman-sys = "0.1.0"
rdw = { package = "rdw4", path = "../rdw4", default-features = false }

[dependencies.qemu-display]
git = "https://gitlab.com/marcandre.lureau/qemu-display.git"
rev = "8ac3da95abeca92e5bb0aee2c58adf54e86f4482"

[target.'cfg(unix)'.dependencies]
usbredirhost = "0.4"
libc = "0.2"

[target.'cfg(windows)'.dependencies]
uds_windows = "1.1.0"
windows = { version = "0.62", features = ["Win32_System_Memory", "Win32_Foundation"] }

[package.metadata.capi.library]
name = "rdw4-qemu"

[package.metadata.capi.header]
name = "rdw-qemu"
subdirectory = "rdw4"
generation = false

[package.metadata.capi.pkg_config]
filename = "rdw4-qemu"
requires = "rdw4"
